### ISSUE TITLE
Linkit smart 7688

### ISSUE THREAD

**Issue by tcpipchip** [crblanaru/mraaupm7688#1]
Do that ipk works on linkit smart 7688 ?

**Comment by crblanaru** [comment]
nope... segfaults... I am trying to understand how to integrate to the latest version, but not being a coder it's doing my head in

**Comment by tcpipchip** [comment]
I decided to compile using MT7620 wrtnode images to execute o on LINKIT....wrtnode has updated libmraa and  libupm source codes...

**Comment by tcpipchip** [comment]
Just compiling now!

**Comment by crblanaru** [comment]
Let me know if it works. The greatest challenge for me is in understanding how to apply the patches correctly against the latest version as both libs have evolved quite a lot.

**Comment by crblanaru** [comment]
What I ended up doing as I needed the bmp280 class is added it individually, and altered the code to reflect a similar component... and it compiled fine.

**Comment by tcpipchip** [comment]
here compiled full using mt7620 wrtnode images....but i need to see if runs on mt7688....i had to use a patch to work with libmupm

**Comment by crblanaru** [comment]
I'll test it as soon as I am home. Hmmmm... where are the ipks you created for me to test?

**Comment by tcpipchip** [comment]
https://github.com/WRTnode/openwrt?files=1

May i send you the ipk to tests ? If yes, wich is your email ?

Miguel

Enviada do meu iPhone

Em 13/10/2017, às 09:35, "crblanaru" <notifications@github.com<mailto:notifications@github.com>> escreveu:


I'll test it as soon as I am home. Hmmmm... where are the ipks you created for me to test?

**Comment by crblanaru** [comment]
Sure thing, crblanaru@gmail.com

**Comment by tcpipchip** [comment]
Patch used
https://github.com/nxhack/openwrt-node-packages/issues/46

Enviada do meu iPhone

Em 13/10/2017, às 09:35, "crblanaru" <notifications@github.com<mailto:notifications@github.com>> escreveu:


I'll test it as soon as I am home. Hmmmm... where are the ipks you created for me to test?

**Comment by tcpipchip** [comment]
Sent! See if install on linkit smart 7688, please!
Miguel

Enviada do meu iPhone

Em 13/10/2017, às 12:19, "crblanaru" <notifications@github.com<mailto:notifications@github.com>> escreveu:


Sure thing, crblanaru@gmail.com<mailto:crblanaru@gmail.com>

**Comment by crblanaru** [comment]
Right, so, first thing first... the files you sent worked well... both installed and tried a couple of examples!
That being said, I think that I did not explain what I am trying to achieve. I was also able to compile the libs as mediatek supports it . My problem is compiling against the most recent version which at the time was libmraa_1.6.1 and libupm_1.2.0. It is there that I am trying to understand, but looking at the current versions I see some movement, so I need to try it out.

**Comment by tcpipchip** [comment]
Ok, thank you so much!
Miguel

Enviada do meu iPhone

Em 13/10/2017, às 13:36, "crblanaru" <notifications@github.com<mailto:notifications@github.com>> escreveu:


Right, so, first thing first... the files you sent worked well... both installed and tried a couple of examples!
That being said, I think that I did not explain what I am trying to achieve. I was also able to compile the libs as mediatek supports it . My problem is compiling against the most recent version which at the time was libmraa_1.6.1 and libupm_1.2.0. It is there that I am trying to understand, but looking at the current versions I see some movement, so I need to try it out.

**Comment by crblanaru** [comment]
Closed as not related to version I'm trying to compile.
